### ISSUE TITLE
Router question

### ISSUE THREAD

**Issue by vallemar** [dlight-js/dlight#63]
I've been looking through the documentation but I haven't found anything about navigation or routing. So my question is, is there something about this and if not, is there something planned?

Thanks!

**Comment by IanDxSSXX** [comment]
Yes there's is!  `Router` is put in the `@dlightjs/components` package because it's a dlight implemented component instead of an internel feature. Check out the implementation [here](https://github.com/dlight-js/components/blob/main/src/Router/Routes.view.ts). Here's [an example](https://github.com/dlight-js/homepage/blob/main/apps/homepage/src/App.view.ts#L84) with lazy loading and fallback component. We plan to write some documentations about all these ecosystem usage these days.

Another usage example:
```js
import { Routes } from "@dlightjs/components"

@View
class MyApp {
  View() {
    Routes({
      ".": View => Home(),  // Directly loading with a prop view
      "hello": () => import("./Hello.view.js"), // Lazy loaing for ./hello path
      "": View => {
         ErrorPage()
         button("back")
      }  // Any other path showing ErrorPage + a button
    })
      .onPathUpdate(path => { console.log(`Path has been changed to ${path}`) })  // Callback when path changes
      .fallback(View => LoadingPage())  // LoadingPage fallback
  }
}
```

**Comment by ansarizafar** [comment]
Router has basic features but for building a production ready app we need more features like navigation guards/hooks, meta fields, view transitions etc. We can use Vue router as a reference. https://router.vuejs.org/installation.html

**Comment by IanDxSSXX** [comment]
New router published! Check it out here https://dlight.dev/ecosystem/components/routes

**Comment by IanDxSSXX** [comment]
closed with new routes  https://dlight.dev/ecosystem/components/routes
